package br.com.myproject3.helpdesk;


import models_db.ChamadoDB;
import models_db.ResponsavelDB;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.myproject3.entities.Responsavel;
import br.com.myproject3.entities.Chamado;


/**
 *
 * @author Leonardo
 */
public final class Tickets extends javax.swing.JFrame {
    ChamadoDB chamadoDB = new ChamadoDB();
    
    /**
     * Creates new form Cadastro
     */
    public Tickets() {
        initComponents();
        popularTabela();
        popularComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        campoStatus = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        botaoSalvar = new javax.swing.JButton();
        botaoDeletar = new javax.swing.JButton();
        campoPesquisar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaTickets = new javax.swing.JTable();
        campoId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoNome = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        campoDescricao = new javax.swing.JTextArea();
        campoResponsavel = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        limpaCampo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("HelpDesk");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("DFGothic-EB", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tickets:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 0, 720, 31);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Titulo");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 60, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Responsavel Tecnico:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(560, 120, 140, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(280, 40, 60, 17);

        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });
        jPanel1.add(campoTitulo);
        campoTitulo.setBounds(10, 60, 250, 30);

        campoStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoStatusActionPerformed(evt);
            }
        });
        jPanel1.add(campoStatus);
        campoStatus.setBounds(550, 60, 240, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoSalvar.setText("Salvar");
        botaoSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarActionPerformed(evt);
            }
        });

        botaoDeletar.setText("Excluir");
        botaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeletarActionPerformed(evt);
            }
        });

        campoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Pesquisar:");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(campoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 272, Short.MAX_VALUE)
                .addComponent(botaoSalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDeletar)
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoSalvar)
                    .addComponent(botaoDeletar)
                    .addComponent(campoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(btnPesquisar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 250, 760, 50);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabelaTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Titulo", "Descricao", "Cliente", "Data", "Responsavel", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaTickets.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaTicketsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaTickets);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 756, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 310, 760, 250);

        campoId.setEditable(false);
        campoId.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        campoId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoIdActionPerformed(evt);
            }
        });
        jPanel1.add(campoId);
        campoId.setBounds(40, 0, 30, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("ID:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 10, 34, 17);
        jPanel1.add(campoNome);
        campoNome.setBounds(280, 60, 250, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Descrição:");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 100, 70, 17);

        campoDescricao.setColumns(20);
        campoDescricao.setRows(5);
        jScrollPane1.setViewportView(campoDescricao);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 120, 520, 120);

        campoResponsavel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoResponsavelActionPerformed(evt);
            }
        });
        jPanel1.add(campoResponsavel);
        campoResponsavel.setBounds(550, 140, 210, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Status");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(550, 40, 70, 17);

        limpaCampo.setText("Limpar Edição");
        limpaCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpaCampoActionPerformed(evt);
            }
        });
        jPanel1.add(limpaCampo);
        limpaCampo.setBounds(550, 210, 220, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void popularComboBox(){
            ResponsavelDB resp = new ResponsavelDB();
        try {
            Responsavel responsavel = new Responsavel();
            for (Responsavel r: resp.getAll()){
                campoResponsavel.addItem(r.getNome());
            }
        }  
        catch(Exception e)  
        {  
            JOptionPane.showMessageDialog(null,   
                "Ocorreu erro ao carregar a Combo Box", "Erro",  
                JOptionPane.ERROR_MESSAGE);  
        }       
 
    }  
    
    public void popularTabela(){
         DefaultTableModel model =(DefaultTableModel) tabelaTickets.getModel();
         model.setNumRows(0);
         ChamadoDB dao = new ChamadoDB();
         try {
             //Se o campo pesquisar for preenchido a tabela pesquisara pelo valor
             if(campoPesquisar.getText().length()>3){
                 Chamado chamado = new Chamado();
                 chamado.setTitulo(campoPesquisar.getText());
                for(Chamado c: dao.getOne(chamado)){
                    model.addRow(new Object[]{
                        c.getId(),
                        c.getTitulo(),
                        c.getDescricao(),
                        c.getNome_cliente(),
                        c.getData_hora_abertura(),
                        c.getNome_responsavel(),
                        c.getStatus()
                        });
                    } 
                JOptionPane.showMessageDialog(null, "A pesquisa retornou "+ model.getRowCount()+" chamados");
                }else {
                    for(Chamado c: dao.getAll()){
                     model.addRow(new Object[]{
                        c.getId(),
                        c.getTitulo(),
                        c.getDescricao(),
                        c.getNome_cliente(),
                        c.getData_hora_abertura(),
                        c.getNome_responsavel(),
                        c.getStatus()
                     });
                 }
             }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Foi encontrado um erro ao buscar dados! Erro: "+ e);
        }

    }
    
    private void botaoSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoSalvarActionPerformed
        //Botão salvar
        Chamado chamado = new Chamado();
        if(campoTitulo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor insira um titulo");
        } else if(campoNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor insira um nome");
        } else {
            chamado.setTitulo(campoTitulo.getText());
            chamado.setNome_cliente(campoNome.getText());
            chamado.setDescricao(campoDescricao.getText());
            chamado.setStatus(campoStatus.getText());
            chamado.setNome_responsavel(campoResponsavel.getSelectedItem().toString());

            //Valida se é edição ou criação
          if(campoId.getText().length()>0){
            chamado.setId(Integer.parseInt(campoId.getText()));
          }
            popularTabela();
            chamadoDB.saveOrUpdate(chamado);
        }
    }//GEN-LAST:event_botaoSalvarActionPerformed

    private void botaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeletarActionPerformed
        //Botão excluir
        Chamado chamado = new Chamado();
        try {
            if(campoId.getText().length()>0){
            chamado.setId(Integer.parseInt(campoId.getText()));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Chamado não encontrado! " + e);
        }
        chamadoDB.delete(chamado);
        popularTabela();
    }//GEN-LAST:event_botaoDeletarActionPerformed

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        popularTabela();
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void campoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisarActionPerformed

    private void tabelaTicketsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaTicketsMouseClicked
        // Pegar dado da linha selecionada e povoando campos
        campoId.setText(tabelaTickets.getValueAt(tabelaTickets.getSelectedRow(),0).toString());
        campoTitulo.setText(tabelaTickets.getValueAt(tabelaTickets.getSelectedRow(),1).toString());
        campoDescricao.setText(tabelaTickets.getValueAt(tabelaTickets.getSelectedRow(),2).toString());
        campoNome.setText(tabelaTickets.getValueAt(tabelaTickets.getSelectedRow(),3).toString());
        campoResponsavel.setSelectedItem(tabelaTickets.getValueAt(tabelaTickets.getSelectedRow(),5).toString());
        campoStatus.setText(tabelaTickets.getValueAt(tabelaTickets.getSelectedRow(),6).toString());
        

       
    }//GEN-LAST:event_tabelaTicketsMouseClicked

    private void campoIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoIdActionPerformed

    private void campoStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoStatusActionPerformed

    private void campoResponsavelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoResponsavelActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_campoResponsavelActionPerformed

    private void limpaCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpaCampoActionPerformed
        // TODO add your handling code here:
        campoId.setText("");
        campoTitulo.setText("");
        campoDescricao.setText("");
        campoNome.setText("");
        campoResponsavel.setSelectedItem("default");
        campoStatus.setText("");
    }//GEN-LAST:event_limpaCampoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Responsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Responsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Responsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Responsavel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cadastro().setVisible(true);
//            }
//        });
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Cadastro().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDeletar;
    private javax.swing.JButton botaoSalvar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea campoDescricao;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNome;
    private javax.swing.JTextField campoPesquisar;
    private javax.swing.JComboBox<String> campoResponsavel;
    private javax.swing.JTextField campoStatus;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton limpaCampo;
    private javax.swing.JTable tabelaTickets;
    // End of variables declaration//GEN-END:variables
}
